spring:
  ai:
    openai:
      api-key: ${SPRING_AI_OPENAI_API_KEY}
      chat:
        options:
          temperature: 0.3
          model: gpt-4-turbo-preview
      embedding:
        options:
          model: text-embedding-3-small
    vectorstore:
      redis:
        index: index-name
        prefix: spring
